import Head from 'next/head'
import { Catalog } from '../components/Catalog/Catalog';
import { Header } from '../components/Header/Header'
import styles from '../styles/Home.module.css'

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Seedlings</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <Catalog />
        </div>
    )
}
